#!/usr/bin/env python3
"""Print `<device> <version>` for each device's newest known firmware.

Reads misc/firmware_versions.txt (regenerated by
scripts/generate_firmware_versions.py) and reduces it to one line per device
model, carrying that model's highest ProductVersion.

Exists because "newest known version for this device MODEL" is the value
bake-firmware threads into the synthetic `firmware` dpkg package and into
stageVersionBranch()'s choice of persistence payload -- NOT a given tuple's own
ProductVersion. See BakeFirmware.cpp's own comment for why. Anything that needs
to resolve packages the way a real bake would needs the same value, and
.github/workflows/debcache.yml is the second such caller.

Versions are compared as integer tuples, not strings: "8.4.6" must sort above
"8.4.10" correctly if such a version ever appears, and "10.x" above "9.x".
"""

import re
import sys
from pathlib import Path

DEFAULT = Path(__file__).resolve().parent.parent / "misc" / "firmware_versions.txt"


def version_key(version):
    return tuple(int(part) for part in re.findall(r"\d+", version))


def newest_per_device(path):
    best = {}
    for line in path.read_text().splitlines():
        parts = line.split("#")[0].split()
        if len(parts) != 3:
            continue
        device, _build, version = parts
        if device not in best or version_key(version) > version_key(best[device]):
            best[device] = version
    return best


def main():
    path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT
    if not path.exists():
        raise SystemExit(f"newest_firmware_versions.py: {path} does not exist")
    best = newest_per_device(path)
    if not best:
        raise SystemExit(f"newest_firmware_versions.py: {path} had no usable data lines")
    for device in sorted(best):
        print(device, best[device])


if __name__ == "__main__":
    main()
